// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Q_U96ril-fRApq7MDvbIl49fqCXa0Gk',
    appId: '1:146312337575:web:b53f3d9fd644bde765e382',
    messagingSenderId: '146312337575',
    projectId: 'hechibrown-4eecf',
    authDomain: 'hechibrown-4eecf.firebaseapp.com',
    storageBucket: 'hechibrown-4eecf.firebasestorage.app',
    measurementId: 'G-2E8WNSZ1LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQO_sAjlzyfSqCeY-d7Ptt2g8gtoP52k',
    appId: '1:146312337575:android:4c6f6621ada8bbbc65e382',
    messagingSenderId: '146312337575',
    projectId: 'hechibrown-4eecf',
    storageBucket: 'hechibrown-4eecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKZ3s7OGXXvcWeb4-Jel0WPuEPoEB39U',
    appId: '1:146312337575:ios:d00e4d78195bdc0665e382',
    messagingSenderId: '146312337575',
    projectId: 'hechibrown-4eecf',
    storageBucket: 'hechibrown-4eecf.firebasestorage.app',
    iosBundleId: 'com.example.hechi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKZ3s7OGXXvcWeb4-Jel0WPuEPoEB39U',
    appId: '1:146312337575:ios:d00e4d78195bdc0665e382',
    messagingSenderId: '146312337575',
    projectId: 'hechibrown-4eecf',
    storageBucket: 'hechibrown-4eecf.firebasestorage.app',
    iosBundleId: 'com.example.hechi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Q_U96ril-fRApq7MDvbIl49fqCXa0Gk',
    appId: '1:146312337575:web:bf9d37f2302ce01165e382',
    messagingSenderId: '146312337575',
    projectId: 'hechibrown-4eecf',
    authDomain: 'hechibrown-4eecf.firebaseapp.com',
    storageBucket: 'hechibrown-4eecf.firebasestorage.app',
    measurementId: 'G-SFT5JBW7CT',
  );
}
